spring:
  application:
    name: anime
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
